added mysql settings to settings.py
RTask/RTask pull request #38
Opened 2020-10-03 05:22 UTC by SoumyaRanjanNaik

added settings for the MySQL in settings.py.
Details that need to be entered or changed are marked with TODOs.

2020-10-06 23:14 UTC, m-henderson commented on rtask/rtask/settings.py
> +SECRET_KEY = "qgw%q&l*_*^pa5r&%82cz4&-71!lhhfe3ujc!z(j(y27@50iiz"
why was this changed?

2020-10-06 23:16 UTC, m-henderson requested changes
Thanks for the PR! could you please remove the unnecessary changes where you changed ' to "?

2020-10-07 04:24 UTC, SoumyaRanjanNaik commented
Sorry, my mistake I use black as my formatter which did this, I will fix it give me some time.

2020-10-07 04:45 UTC, SoumyaRanjanNaik commented
@m-henderson please check now this should be according to your requirements.

2020-10-07 12:10 UTC, m-henderson requested changes
looks good and is almost ready to merge. Could you please remove that "if DEBUG"  comment from lines 76 to 83?

2020-10-07 12:15 UTC, SoumyaRanjanNaik commented
> looks good and is almost ready to merge. Could you please remove that "if DEBUG" comment from lines 76 to 83?

Actually that line will help you to keep proper separation between your development and production environments by switching between databases based on the DEBUG value.

May I uncomment the condition so you can see it working ?

2020-10-07 12:30 UTC, m-henderson commented
> > looks good and is almost ready to merge. Could you please remove that "if DEBUG" comment from lines 76 to 83?
> 
> Actually that line will help you to keep proper separation between your development and production environments by switching between databases based on the DEBUG value.
> 
> May I uncomment the condition so you can see it working ?

This is not the best way to manage different environment variables. For example, it's better to create a different settings file for dev, qa, prod, that contains the values that should be overridden. Then, the correct settings will be run for the corresponding environment the app is in. So, If I am in dev then dev_settings.py should run and override only certain values in settings.py. I will remove the comment because I am pulling down the code to test it anyway :)

2020-10-07 12:38 UTC, m-henderson commented
@SoumyaRanjanNaik actually, I just tried to make the changes and it is being a pain. Could you make the changes? I will leave comments in the file.

2020-10-07 12:39 UTC, SoumyaRanjanNaik commented
okay sure.

2020-10-07 12:39 UTC, m-henderson requested changes
ok. get those comments fixed up and it will be ready to merge.

2020-10-07 12:39 UTC, m-henderson commented on rtask/rtask/settings.py
> +# if DEBUG:
please remove this if else comment block

2020-10-07 12:39 UTC, m-henderson commented on rtask/rtask/settings.py
> +        "NAME": "",  # TODO: Database Name
please remove this TODO comment. There is nothing to do here.

2020-10-07 12:39 UTC, m-henderson commented on rtask/rtask/settings.py
> +        "USER": "",  # TODO: username for the database
please remove this TODO comment. There is nothing to do here.

2020-10-07 12:39 UTC, m-henderson commented on rtask/rtask/settings.py
> +        "PASSWORD": "",  # TODO : Password for Database
please remove this TODO comment. There is nothing to do here.

2020-10-07 12:39 UTC, m-henderson commented on rtask/rtask/settings.py
> +        "HOST": "localhost",  # TODO: replace this with hostname in production
please remove this TODO comment. There is nothing to do here.

2020-10-07 13:01 UTC, m-henderson commented on rtask/rtask/settings.py
> +        "NAME": "",  # Database Name
no need for comments. we know that is the database name, username, password, and host.

2020-10-07 13:03 UTC, m-henderson commented
@SoumyaRanjanNaik take care of that one last comment and your good.

2020-10-07 13:16 UTC, m-henderson approved these changes

2020-10-07 13:16 UTC, merged